version: '3.7'

services:
  cars:
    build: "../dockerizedApps/Lab3Cars"
    expose:
      - "8082"

  users:
    build: "../dockerizedApps/Lab3Users"
    expose:
      - "8081"
    depends_on:
      - "cars"

  gateway:
    build: "../dockerizedApps/lab3Gateway"
    expose:
      - "8080"

  frontend:
    build: "../dockerizedApps/frontend/app"
    expose:
      - "8083"

  proxy:
    build: "../Lab5nginx"
    ports: 
      - "80:80"
