version: '3.7'

services:
  cars:
    build: "../dockerizedApps/Lab3Cars"
    expose:
      - "8082"

  users:
    build: "../dockerizedApps/Lab3Users"
    expose:
      - "8081"
    depends_on:
      - "cars"

  # vue:
  #   build: "../Lab4"
  #   ports: 
  #     - "8080:8083"
  #   depends_on:
  #     - cars
  #     - users
  
  gateway:
    build: "../dockerizedApps/lab3Gateway"
    expose:
      - "8080"
    ports:
      - ":8080"

  proxy:
    build: "../Lab5nginx"
    ports: 
      - "80:80"

